<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-DSM3BH7" ignored="0" name="Default test(failed)" tests="2" failures="2" timestamp="06 Mar 2017 18:53:44 GMT" time="37.099" errors="0">
  <testcase name="Login_Validation" time="18.796" classname="TestNG.DataProvider_Example">
    <failure type="java.lang.AssertionError" message="User is unable to login - Incorrect credentials expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: User is unable to login - Incorrect credentials expected [true] but found [false]
	at TestNG.DataProvider_Example.Login_Validation(DataProvider_Example.java:30)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Login_Validation -->
  <testcase name="Login_Validation" time="15.184" classname="TestNG.DataProvider_Example">
    <failure type="java.lang.AssertionError" message="User is unable to login - Incorrect credentials expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: User is unable to login - Incorrect credentials expected [true] but found [false]
	at TestNG.DataProvider_Example.Login_Validation(DataProvider_Example.java:30)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- Login_Validation -->
</testsuite> <!-- Default test(failed) -->
